### ISSUE TITLE
Error fetching identities

### ISSUE THREAD

**Issue by ntaken** [anaisbetts/ssh-agent-relay#5]
Hello!

Followed your instructions and my ssh-agent works fine on the windows side but when I try ssh-add -l it fails in WSL2.

ssh-add -l
`error fetching identities: communication with agent failed`

Of course ssh also fails to communicate with the windows ssh-agent.

Do you have any ideas?

I tried to reinstall entire Ubuntu without success.

My setup:
Windows 10 Enterprise 20H2 19042.867
WSL2 - Ubuntu
WSL2 also have windows docker integration.

**Comment by ntaken** [comment]
Interestingly at my home computer with a similar setup except with Windows 10 Pro (21H1 19043.906) it works fine. 

So it seems the problem is either some group policy or Enterprise. It have been a bit hard to troubleshoot. So any ideas would be helpful.

Also on the working home computer I have only an admin user. 

On the Enterprise I have one ordinary everyday user and a seperate admin user when needed.

**Comment by anaisbetts** [comment]
Hi, you should use https://github.com/arquivolta/wsl-use-windows-openssh instead!
